# Week 7 Independent lab

**Course Information:**  Graduate Introduction to Python, BGEN 632

**Notebook Author Name:** Leo Valladares

**Submission Date:**  2025/04/14

**Description:**  This project process data from a hospital data set from California.

### Import Modules

In [3]:
import os
import pandas as pd
import numpy as np

### Set Working Directory

In [5]:
os.chdir("C:/Users/leova/OneDrive/BGEN 632/week7labs/data")

### Access Data

In [7]:
# Open the file within Python
hospital_data = pd.read_csv("CaliforniaHospitalData.csv")
employee_data = pd.read_csv("CaliforniaHospitalData_Personnel.txt", sep="\t")

In [8]:
hospital_data.head(5)

,HospitalID,Name,Zip,Website,TypeControl,Teaching,DonorType,NoFTE,NetPatRev,InOperExp,OutOperExp,OperRev,OperInc,AvlBeds
0,45740,Mammoth Hospital,93546-0660,www.mammothhospital.com,District,Small/Rural,Charity,327.0,135520.2186,20523425.53,34916220.47,49933713,-5505933,15
1,12145,Victor Valley Community Hospital,92392,www.vvch.org,Non Profit,Small/Rural,Charity,345.0,136156.6913,33447542.78,20348596.22,53351748,-444391,99
2,25667,Pioneers Memorial Hospital,92227,www.pmhd.org,District,Small/Rural,Charity,601.2,197094.2541,37254178.67,37832448.33,72933707,-2152920,107
3,46996,Ridgecrest Regional Hospital,93555,www.rrh.org,Non Profit,Small/Rural,Charity,400.0,139170.3798,23385570.10,24661355.90,51087341,3040415,55
4,37393,Barstow Community Hospital,92311,www.barstowhospital.com,Investor,Small/Rural,Charity,262.0,116797.8306,13684502.49,15159986.51,42845642,14001153,42

### Merging the Data

In [10]:
merge_df = hospital_data.merge(employee_data, how='inner', on='HospitalID')
merge_df.columns

Index(['HospitalID', 'Name', 'Zip', 'Website', 'TypeControl', 'Teaching',
       'DonorType', 'NoFTE', 'NetPatRev', 'InOperExp', 'OutOperExp', 'OperRev',
       'OperInc', 'AvlBeds', 'Work_ID', 'LastName', 'FirstName', 'Gender',
       'PositionID', 'PositionTitle', 'Compensation', 'MaxTerm', 'StartDate',
       'Phone', 'Email'],
      dtype='object')

### Droping columns

In [12]:
merge_df = merge_df.drop(['Work_ID', 'PositionID','Website'], axis = 1)
merge_df.columns
# There are no duplicated columns

Index(['HospitalID', 'Name', 'Zip', 'TypeControl', 'Teaching', 'DonorType',
       'NoFTE', 'NetPatRev', 'InOperExp', 'OutOperExp', 'OperRev', 'OperInc',
       'AvlBeds', 'LastName', 'FirstName', 'Gender', 'PositionTitle',
       'Compensation', 'MaxTerm', 'StartDate', 'Phone', 'Email'],
      dtype='object')

## Exporting the Data

In [14]:
# Filter data
export_df = merge_df[(merge_df.Teaching == 'Small/Rural') & (merge_df.AvlBeds >= 15) & ( merge_df.OperInc > 0)] 

# Export file 
merge_df.to_csv('hospital_data_new.txt', index=False)

## Renaming Columns

In [16]:
# Import new data frame
new_df = pd.read_csv("hospital_data_new.txt")

# change column names
new_df = new_df.rename(columns = {
    'NoFTE': 'FullTimeCount',
    'NetPatRev': 'NetPatientRevenue',
    'InOperExp': 'InpatientOperExp',
    'OutOperExp': 'OutpatientOperExp',
    'OperRev': 'Operating_Revenue',
    'OperInc': 'Operating_Income'   
})

new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   HospitalID         61 non-null     int64
 1   Name               61 non-null     object
 2   Zip                61 non-null     object
 3   TypeControl        61 non-null     object
 4   Teaching           61 non-null     object
 5   DonorType          61 non-null     object
 6   FullTimeCount      61 non-null     float64
 7   NetPatientRevenue  61 non-null     float64
 8   InpatientOperExp   61 non-null     float64
 9   OutpatientOperExp  61 non-null     float64
 10  Operating_Revenue  61 non-null     int64
 11  Operating_Income   61 non-null     int64
 12  AvlBeds            61 non-null     int64
 13  LastName           61 non-null     object
 14  FirstName          61 non-null     object
 15  Gender             61 non-null     object
 16  PositionTitle      61 non-null     object
 17  Compensation       61 non-null     int64
 18  MaxTerm            61 non-null     int64
 19  StartDate          61 non-null     object
 20  Phone              61 non-null     object
 21  Email              61 non-null     object
dtypes: float64(4), int64(6), object(12)
memory usage: 10.6+ KB

## Inserting Records

In [18]:
new_rows = new_df.iloc[[2,5],].reset_index()       # Pull 2 rows from the data set and reset the index
new_rows = new_rows.drop(['index'], axis = 1)      # Remove the index column 

# Replace the values needed
new_rows.iloc[:2, 13] = 'Valladares'
new_rows.iloc[:2, 14] = 'Leo'
new_rows.iloc[:2, 16] = 'State Board Representative'
new_rows.iloc[:2, 17] = 89473
new_rows.iloc[:2, 18] = 3
new_rows.iloc[:2, 19] = '04/14/2025'
new_rows.iloc[:2, 20] = '406-123-4567'
new_rows.iloc[:2, 21] = 'leo.valladares@mus.med'
new_rows

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,25667,Pioneers Memorial Hospital,92227,District,Small/Rural,Charity,601.2,197094.2541,37254178.67,37832448.33,...,107,Valladares,Leo,M,State Board Representative,89473,3,04/14/2025,406-123-4567,leo.valladares@mus.med
1,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.5,232503.0191,36682888.70,36739260.30,...,66,Valladares,Leo,M,State Board Representative,89473,3,04/14/2025,406-123-4567,leo.valladares@mus.med

In [19]:
# Merge new rows to the data frame
new_merge = pd.concat([new_df, new_rows], ignore_index = True)
new_merge

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,45740,Mammoth Hospital,93546-0660,District,Small/Rural,Charity,327.0,1.355202e+05,2.052343e+07,3.491622e+07,...,15,Web,David,M,Safety Inspection Member,23987,2,1/1/2012,785-532-2452,david.web@comenitymed.com
1,12145,Victor Valley Community Hospital,92392,Non Profit,Small/Rural,Charity,345.0,1.361567e+05,3.344754e+07,2.034860e+07,...,99,Rodriguez,Jose,M,Regional Representative,46978,4,1/1/2009,405-744-2238,jose.rodriguez@edihealth.com
2,25667,Pioneers Memorial Hospital,92227,District,Small/Rural,Charity,601.2,1.970943e+05,3.725418e+07,3.783245e+07,...,107,Adamson,David,M,Regional Representative,46978,4,1/1/2012,785-532-7573,david.adamson@txbiomed.net
3,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.0,1.391704e+05,2.338557e+07,2.466136e+07,...,55,Roberts,Melissa,F,Safety Inspection Member,23987,2,1/1/2009,785-532-9779,melissa.roberts@txbiomed.net
4,37393,Barstow Community Hospital,92311,Investor,Small/Rural,Charity,262.0,1.167978e+05,1.368450e+07,1.515999e+07,...,42,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,22460,Stanford Hospital & Clinics,94305,Non Profit,Teaching,Alumni,6392.0,4.333934e+06,9.289621e+08,6.621559e+08,...,445,Smith,Mary,F,Safety Inspection Member,23987,2,1/1/2012,469-767-5485,mary.smith@ihc.com
59,33192,California Pacific Medical Center - Pacific Ca...,94115,Non Profit,Teaching,Alumni,1565.1,2.736281e+06,6.337903e+08,2.960207e+08,...,730,Fourier,Craig,M,Regional Representative,46978,4,1/1/2011,503-235-4877,craig.fourier@comenitymed.com
60,38900,Cedars-Sinai Medical Center,90048,Non Profit,Teaching,Alumni,8000.0,4.662582e+06,1.285631e+09,4.616758e+08,...,909,Paanua,Kaaluai,M,Regional Representative,46978,4,1/1/2011,479-684-1883,kaaluai.paanua@brokenhealth.com
61,25667,Pioneers Memorial Hospital,92227,District,Small/Rural,Charity,601.2,1.970943e+05,3.725418e+07,3.783245e+07,...,107,Valladares,Leo,M,State Board Representative,89473,3,04/14/2025,406-123-4567,leo.valladares@mus.med
62,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.5,2.325030e+05,3.668289e+07,3.673926e+07,...,66,Valladares,Leo,M,State Board Representative,89473,3,04/14/2025,406-123-4567,leo.valladares@mus.med

## Filtering Data

In [21]:
# select all hospitals that are non-profit with more than 250 employees, unless the net patient revenue is smaller than $109,000.
filter_df_1 = new_merge[((new_merge.TypeControl == 'Non Profit') & (new_merge.FullTimeCount >= 250)) & (new_merge.NetPatientRevenue >= 109000)]
filter_df_1 = filter_df_1.iloc[:, :13]  # remove employee data
                                 
filter_df_1.head(5)

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,Operating_Revenue,Operating_Income,AvlBeds
1,12145,Victor Valley Community Hospital,92392,Non Profit,Small/Rural,Charity,345.0,136156.6913,3.344754e+07,20348596.22,53351748,-444391,99
3,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.0,139170.3798,2.338557e+07,24661355.90,51087341,3040415,55
5,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.5,232503.0191,3.668289e+07,36739260.30,85808509,12386360,66
6,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.5,214516.4481,3.270922e+07,43571851.35,79005075,2724001,65
9,13738,St. Mary Medical Center,92307-2206,Non Profit,Small/Rural,Charity,1216.0,540975.1175,1.251283e+08,66801544.65,199873795,7943967,186

In [22]:
# Using the `new_merge` data, select all the *Regional Representatives* who work at a hospital with operating income greater than $100,000. Save this as a new DataFrame.
filter_df_2 = new_merge[(new_merge.PositionTitle == 'Regional Representative') & (new_merge.Operating_Income > 100000)]
                                
filter_df_2.head(5)

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
4,37393,Barstow Community Hospital,92311,Investor,Small/Rural,Charity,262.0,116797.8306,13684502.49,15159986.51,...,42,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
6,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.5,214516.4481,32709222.65,43571851.35,...,65,Johanson,Sandy,F,Regional Representative,46978,4,1/1/2012,801-216-4821,sandy.johanson@ihc.com
10,38798,Goleta Valley Cottage Hospital,93111,Non Profit,Small/Rural,Charity,288.0,335179.5574,53589036.09,67030147.91,...,119,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
11,46348,Barton Memorial Hospital,96150,Non Profit,Small/Rural,Charity,750.0,335179.5574,53589036.09,67030147.91,...,119,Paanua,Kaaluai,M,Regional Representative,46978,4,1/1/2011,479-684-1883,kaaluai.paanua@brokenhealth.com
14,17718,Mercy Medical Center - Mount Shasta,96067,Non Profit,Small/Rural,Charity,215.5,123480.2705,22003500.15,22410053.85,...,60,Charles,Kenneth,M,Regional Representative,46978,4,1/1/2009,405-744-3412,kenneth.charles@edihealth.com

## Convert Date-Time Data

In [24]:
# Convert any date-time columns into a datetime datatype. Confirm your changes by outputting the data types for all columns. 
# Additionally, output the first 5 records of the column(s) you converted.

new_merge['StartDate'] = pd.to_datetime(new_merge['StartDate'])
new_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   HospitalID         63 non-null     int64
 1   Name               63 non-null     object
 2   Zip                63 non-null     object
 3   TypeControl        63 non-null     object
 4   Teaching           63 non-null     object
 5   DonorType          63 non-null     object
 6   FullTimeCount      63 non-null     float64
 7   NetPatientRevenue  63 non-null     float64
 8   InpatientOperExp   63 non-null     float64
 9   OutpatientOperExp  63 non-null     float64
 10  Operating_Revenue  63 non-null     int64
 11  Operating_Income   63 non-null     int64
 12  AvlBeds            63 non-null     int64
 13  LastName           63 non-null     object
 14  FirstName          63 non-null     object
 15  Gender             63 non-null     object
 16  PositionTitle      63 non-null     object
 17  Compensation       63 non-null     int64
 18  MaxTerm            63 non-null     int64
 19  StartDate          63 non-null     datetime64[ns]
 20  Phone              63 non-null     object
 21  Email              63 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(6), object(11)
memory usage: 11.0+ KB

## References

OpenAI. (2025). ChatGPT (GPT-4.0) [Large language model]. https://chatgpt.com/share/67fd6b24-0180-8000-bb27-221188dab19e