# Week 7 Instructor lab

**Course Information:**  Graduate Introduction to Python, BGEN 632

**Notebook Author Name:** Leo Valladares

**Submission Date:**  2025/04/14

**Description:** This project processes data frames with pandas and basic Python. 

### Import Modules

In [4]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold

### Set Working Directory

In [6]:
os.chdir("C:/Users/leova/OneDrive/BGEN 632/week7labs/data")

### Access Data

In [8]:
# Open the file within Python
gh_teams = pd.read_csv("github_teams.csv")

### Inspect columns

In [10]:
# Find out what the column header names are
gh_teams.columns

Index(['name_h', 'Team_type', 'Team_size_class', 'human_members_count',
       'bot_members_count', 'human_work', 'work_per_human', 'human_gini',
       'human_Push', 'human_IssueComments', 'human_PRReviewComment',
       'human_MergedPR', 'bot_work', 'bot_Push', 'bot_IssueComments',
       'bot_PRReviewComment', 'bot_MergedPR', 'eval_survival_day_median',
       'issues_count'],
      dtype='object')

In [11]:
# Determine the number of columns
column_number = len(gh_teams.columns)
print(f"There are {column_number} columns in the dataframne")

There are 19 columns in the dataframne

In [12]:
# Determine the number of rows
row_number = len(gh_teams.index)
print(f"There are {row_number} rows in the dataframne")

There are 608 rows in the dataframne

In [13]:
# Determine which columns are categorical and convert them from *object* to *category*
# Explore the data frame
gh_teams.select_dtypes(include = ['object'])

                                            name_h  Team_type Team_size_class
0    _1bqaxzCk0sfQaunsjeViQ/RCEZ3CASdLXbstu9y2JQ7Q  human-bot           Small
1    _9o07rGiC7DFyi-zm91Q0g/VOgMsrjYEwFAq0BY8kHqGQ      human           Small
2    _DzK53uaZXnAX3WcC0W28g/Epc4QWw5PNBQIIdvopEHDA      human           Large
3    _l5u7I5p4thtW5SjR_9_4w/aZNCdVXta7fh7eCMzZP1CA  human-bot           Large
4    _l5u7I5p4thtW5SjR_9_4w/m_FpD7PKQHqVXHn2bh7u2g  human-bot           Large
..                                             ...        ...             ...
603  zTj5tlMWgotzJmQl7BP8wQ/iQ914_smScbUO8BI9JlE6A  human-bot           Small
604  zUBexdmYylGGpxiebXm6gg/sJXD2kulWzU35ijdY3SnBQ      human           Small
605  zVSBi-iRKCzLiqFwVt6hbg/8SfUBIOeWUjDoQxeUCX7wQ      human          Medium
606  zVSBi-iRKCzLiqFwVt6hbg/fm_lDWwc8Uu-aZ24BjUNZg      human          Medium
607  ZX09uvu0z_JVPVI-XrPniQ/pxiuGX_R6QI2Euvx2GFIFw  human-bot           Small

[608 rows x 3 columns]

In [14]:
# convert columns from *object* to *category*
gh_teams['name_h'] = gh_teams['name_h'].astype("category")
gh_teams['Team_type'] = gh_teams['Team_type'].astype("category")
gh_teams['Team_size_class'] = gh_teams['Team_size_class'].astype("category")
gh_teams.select_dtypes(include = ['object'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[608 rows x 0 columns]

In [15]:
# How many unique values does `Team_type` have?
gh_teams.Team_type.unique()

['human-bot', 'human']
Categories (2, object): ['human', 'human-bot']

In [16]:
# How many unique values does `Team_size_class` have?
gh_teams.Team_size_class.unique()

['Small', 'Large', 'Medium']
Categories (3, object): ['Large', 'Medium', 'Small']

In [17]:
# What is the value of the 63rd row and 6th column?
gh_teams.iloc[64, 7]

0.0306122448979591

In [18]:
# What are the values for the 300th row?
gh_teams.iloc[301]

name_h                      j9wc2HRCyP7cJecuXHvGtA/aSJGod8SfdlMjqys9HJuqA
Team_type                                                           human
Team_size_class                                                     Small
human_members_count                                                     3
bot_members_count                                                       0
human_work                                                             47
work_per_human                                                  15.666667
human_gini                                                       0.382979
human_Push                                                             47
human_IssueComments                                                     0
human_PRReviewComment                                                   0
human_MergedPR                                                          0
bot_work                                                                0
bot_Push                                                                0
bot_IssueComments                                                       0
bot_PRReviewComment                                                     0
bot_MergedPR                                                            0
eval_survival_day_median                                              NaN
issues_count                                                          NaN
Name: 301, dtype: object

In [19]:
# Using three different methods, select row with index value 595 with 1st, 2nd, 3rd columns
# First method
gh_teams.iloc[[595],[0, 1, 2]]

                                            name_h  Team_type Team_size_class
595  zAh1NECRCquqUJ_-1d6hAw/DET3jTK8hokYfY_neJ1IVQ  human-bot           Small

In [20]:
# Second method slicing
gh_teams.iloc[595, :3]

name_h             zAh1NECRCquqUJ_-1d6hAw/DET3jTK8hokYfY_neJ1IVQ
Team_type                                              human-bot
Team_size_class                                            Small
Name: 595, dtype: object

In [21]:
# third method Label-based Indexing
gh_teams.loc[595, 'name_h':'Team_size_class']

name_h             zAh1NECRCquqUJ_-1d6hAw/DET3jTK8hokYfY_neJ1IVQ
Team_type                                              human-bot
Team_size_class                                            Small
Name: 595, dtype: object

In [22]:
# Using two different methods, select the row with index value 46 with the 3rd and 7th columns.
# First method
gh_teams.iloc[[46],[2, 6]]

   Team_size_class  work_per_human
46          Medium       31.833333

In [23]:
# second method Label-based Indexing
gh_teams.loc[46, ['Team_size_class','work_per_human']]

Team_size_class       Medium
work_per_human     31.833333
Name: 46, dtype: object

In [24]:
# Create a new DataFrame for the column `bot_work` using two different methods
# first method
bot_work_df = pd.DataFrame(gh_teams['bot_work'])
bot_work_df.head(5)

   bot_work
0        43
1         0
2         0
3      1972
4       302

In [25]:
# second method
bot_work_df = pd.DataFrame(gh_teams.iloc[:, 12])
bot_work_df.head(5)

   bot_work
0        43
1         0
2         0
3      1972
4       302

## Sorting and Ordering data

In [27]:
# Select `human-bot` teams that have a `bot_members_count` value greater than and equal to 2.
gh_teams[(gh_teams.Team_type == 'human-bot') & (gh_teams.bot_members_count >= 2)]

,name_h,Team_type,Team_size_class,human_members_count,bot_members_count,human_work,work_per_human,human_gini,human_Push,human_IssueComments,human_PRReviewComment,human_MergedPR,bot_work,bot_Push,bot_IssueComments,bot_PRReviewComment,bot_MergedPR,eval_survival_day_median,issues_count
3,_l5u7I5p4thtW5SjR_9_4w/aZNCdVXta7fh7eCMzZP1CA,human-bot,Large,234,12,14579,62.303419,0.738342,1942,11430,1170,37,1972,0,1972,0,0,1.0,4757.0
4,_l5u7I5p4thtW5SjR_9_4w/m_FpD7PKQHqVXHn2bh7u2g,human-bot,Large,38,8,1625,42.763158,0.666607,203,1270,152,0,302,0,302,0,0,2.0,777.0
42,2-scMrZv13F95YPZmfieww/4Zc56iUYjIZrZU06omFrJw,human-bot,Large,23,2,4648,202.086957,0.560241,864,2574,1174,36,1325,0,1325,0,0,11.0,1635.0
84,4YoH8row044yJjPIqWJw9Q/NSXj3i61X71lV0StTN71Ww,human-bot,Small,2,2,114,57.000000,0.491228,114,0,0,0,37,0,37,0,0,0.0,14.0
89,5Is-_ie16OEGmW1arZm8qg/8UeSk2P76pTG7pPLtxsHTQ,human-bot,Large,17,4,7412,436.000000,0.439621,4182,1257,1917,56,358,5,202,151,0,2.0,495.0
110,7sA-8-nyqr0Ri2CT4-FSZw/GJPQoUhHfvUsxKcdkHWLEw,human-bot,Small,3,2,244,81.333333,0.502732,171,73,0,0,136,0,136,0,0,1.0,41.0
146,bi5TY2Z4OSQq3PMs6JnKYA/5wtZcUUo1XmLHIra8NDtFQ,human-bot,Medium,4,2,170,42.500000,0.717647,144,7,19,0,104,0,104,0,0,NaN,NaN
147,bi5TY2Z4OSQq3PMs6JnKYA/9b9IqkDK14ketwn88f3hKA,human-bot,Small,3,2,189,63.000000,0.624339,174,10,5,0,125,0,125,0,0,35.0,9.0
149,bi5TY2Z4OSQq3PMs6JnKYA/kIiAIJpk6lOa6Nxf234KkQ,human-bot,Small,3,2,88,29.333333,0.636364,74,7,7,0,74,0,74,0,0,NaN,NaN
224,FAhkB4rsocfDW0vrM8U8NA/3KHgTzOwWtAxTXlp_mbqoA,human-bot,Large,15,2,4821,321.400000,0.689096,2564,1801,386,70,270,90,116,52,12,13.0,1522.0
229,FAhkB4rsocfDW0vrM8U8NA/Tl_ZLGwQZrAi-GHyEKl_jA,human-bot,Large,18,2,2328,129.333333,0.680126,573,795,960,0,117,12,66,39,0,22.0,303.0
231,FAhkB4rsocfDW0vrM8U8NA/zHikYkcLoXRCKt2cUrRvvg,human-bot,Large,17,2,816,48.000000,0.683824,177,447,192,0,217,45,113,59,0,11.0,241.0
268,hXoZRbHPbVxh--funPXSiw/iNU0l_SpKVjGfHOp8vUt8w,human-bot,Small,2,2,910,455.000000,0.065934,207,369,334,0,114,0,114,0,0,4.0,64.0
325,kpY6vTbIlrk6Nrjilv8zhw/o_e0F16zwdovR3aFgIQipQ,human-bot,Large,29,2,2891,99.689655,0.752705,762,1793,302,34,790,1,789,0,0,7.0,1283.0
331,LDm8GbdhrDbcBGJF0dR_5g/-L63SLGp3n6MA-y5Di59og,human-bot,Large,18,2,840,46.666667,0.579894,118,603,113,6,79,0,79,0,0,16.0,369.0
345,MC6oqT7o22Y_rULWJZllfA/MXyVzmYYom7cgybNB0CjFQ,human-bot,Large,7,2,1421,203.000000,0.504072,444,277,644,56,77,0,77,0,0,19.0,124.0
376,O8b2IFn80coqzdP6IwbEKg/uAklmRuq-bJgMfb-PuSjSg,human-bot,Medium,4,2,35,8.750000,0.350000,22,13,0,0,26,0,26,0,0,NaN,NaN
413,Q658evmRIuaDEnUGlBqzYw/m-hxXTPKmxu3fh32f-RHtg,human-bot,Small,2,2,256,128.000000,0.425781,230,5,21,0,118,0,118,0,0,0.0,7.0
441,ReeJIVTm1BiV_SO5tNDVFA/ZfIj2C4Weg8to684MM7PGA,human-bot,Large,15,2,2211,147.400000,0.544068,214,1312,685,0,50,0,47,3,0,9.0,6.0
472,sq4hB0bA5jL3X3tvK_-stg/5YplqVgfP__pUXTJ9SMoQA,human-bot,Medium,4,2,484,121.000000,0.626033,304,180,0,0,298,0,298,0,0,12.0,92.0
473,sq4hB0bA5jL3X3tvK_-stg/G5WoDm7Rms4zNbJ3nc6hZA,human-bot,Large,27,2,2282,84.518519,0.815302,933,1275,74,0,475,0,457,0,18,2.0,603.0
541,vPPJXk7AxaaZyPsmA3MniQ/euqt0qlPNtbUnKy41316mA,human-bot,Medium,4,2,297,74.250000,0.521044,275,5,0,17,177,0,167,0,10,0.0,20.0
568,X1pcjhqqelcsRxAhcbNu-w/HJ1fkoQOuwxXJ25L7FGEcw,human-bot,Medium,5,2,281,56.200000,0.422776,95,94,85,7,51,0,51,0,0,64.0,25.0
586,YQI5l7pwpiRU8KVKXkNjjg/fCxq0R6_z233Fdr2Ly6iug,human-bot,Medium,5,2,1644,328.800000,0.560341,214,997,433,0,684,251,433,0,0,4.0,45.0

In [28]:
# Find the `human` teams that are `Large` and have a `human_gini` value greater than and equal to 0.75.
gh_teams[(gh_teams.Team_type == 'human') &
(gh_teams.Team_size_class == 'Large') &
(gh_teams.human_gini >= 0.75)]

,name_h,Team_type,Team_size_class,human_members_count,bot_members_count,human_work,work_per_human,human_gini,human_Push,human_IssueComments,human_PRReviewComment,human_MergedPR,bot_work,bot_Push,bot_IssueComments,bot_PRReviewComment,bot_MergedPR,eval_survival_day_median,issues_count
138,ASYGR96YA91p3z7MNKjZCA/IB2pZ8ygcvNnlxUdysjSFA,human,Large,12,0,1655,137.916667,0.799446,793,684,178,0,0,0,0,0,0,4.0,190.0
285,IiUao8vA_zm_uEIVVLI-Sw/91ya8vlSP8qgwCllH_6BSw,human,Large,25,0,3599,143.960000,0.863507,1249,2350,0,0,0,0,0,0,0,0.0,1245.0
505,uLHPO58cQefwrJUbyhYOKQ/7YWOP8uDEeKDHQMWKqOoYA,human,Large,48,0,5748,119.750000,0.782040,1715,3891,142,0,0,0,0,0,0,0.0,1200.0
582,y8Jw59EHVSrsluSuhR5okg/V5vb074jNkzg4YCKforX1Q,human,Large,8,0,277,34.625000,0.781137,275,2,0,0,0,0,0,0,0,NaN,NaN

In [29]:
# How many teams are in the `Small` or `Large` category?
teams_number = len(gh_teams[(gh_teams.Team_size_class == 'Large') | (gh_teams.Team_size_class == 'Small') ])
print(f"There are {teams_number} small or lager teams")

There are 428 small or lager teams

In [30]:
# How many teams are in the `Small` or `Large` category with a `human_gini` value less than and equal to 0.20?
teams_number_2 = len(gh_teams[((gh_teams.Team_size_class == 'Large') | (gh_teams.Team_size_class == 'Small')) &
                     (gh_teams.human_gini <= 0.2)])
print(f"There are {teams_number_2} small or lager teams a with a human_gini value less than and equal to 0.20")

There are 66 small or lager teams a with a human_gini value less than and equal to 0.20

In [31]:
# How many `human-bot` teams are in the `Medium` category?
teams_number_3 = len(gh_teams[(gh_teams.Team_type == 'human-bot') &
(gh_teams.Team_size_class == 'Medium')])

print(f"There are {teams_number_3} human-bot teams whit a Medium category")

There are 84 human-bot teams whit a Medium category

In [32]:
# Create a subsample of 50% of your data.
gh_teams_subsample = gh_teams.sample(frac = 0.5, replace = False)
len(gh_teams_subsample.index)

304

In [33]:
# Create samples for a 8-fold cross validation test
kf = KFold(n_splits = 8)  # K-Fold cross-validator with 8 folds 

for train, test in kf.split(gh_teams):
    print("%s %s" % (train, test))

[ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273
 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291
 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309
 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327
 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345
 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363
 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399
 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435
 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273
 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291
 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309
 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327
 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345
 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363
 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399
 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435
 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273
 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291
 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309
 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327
 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345
 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363
 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399
 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435
 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187
 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 304 305 306 307 308 309
 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327
 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345
 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363
 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399
 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435
 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245
 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263
 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281
 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299
 300 301 302 303]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399
 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435
 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321
 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339
 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357
 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375
 376 377 378 379]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451
 452 453 454 455]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597
 598 599 600 601 602 603 604 605 606 607] [456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473
 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491
 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509
 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527
 528 529 530 531]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531] [532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549
 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567
 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585
 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603
 604 605 606 607]

In [34]:
# Select columns that are numeric and save it as a new DataFrame
numeric_df = pd.DataFrame(gh_teams.select_dtypes(include = ['int64','float64']))
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   human_members_count       608 non-null    int64
 1   bot_members_count         608 non-null    int64
 2   human_work                608 non-null    int64
 3   work_per_human            608 non-null    float64
 4   human_gini                608 non-null    float64
 5   human_Push                608 non-null    int64
 6   human_IssueComments       608 non-null    int64
 7   human_PRReviewComment     608 non-null    int64
 8   human_MergedPR            608 non-null    int64
 9   bot_work                  608 non-null    int64
 10  bot_Push                  608 non-null    int64
 11  bot_IssueComments         608 non-null    int64
 12  bot_PRReviewComment       608 non-null    int64
 13  bot_MergedPR              608 non-null    int64
 14  eval_survival_day_median  303 non-null    float64
 15  issues_count              303 non-null    float64
dtypes: float64(4), int64(12)
memory usage: 76.1 KB

In [35]:
#  Remove the columns `bot_PRReviewComment` and `bot_MergedPR` from the DataFrame.
numeric_df = numeric_df.drop(['bot_PRReviewComment', 'bot_MergedPR',], axis = 1)
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   human_members_count       608 non-null    int64
 1   bot_members_count         608 non-null    int64
 2   human_work                608 non-null    int64
 3   work_per_human            608 non-null    float64
 4   human_gini                608 non-null    float64
 5   human_Push                608 non-null    int64
 6   human_IssueComments       608 non-null    int64
 7   human_PRReviewComment     608 non-null    int64
 8   human_MergedPR            608 non-null    int64
 9   bot_work                  608 non-null    int64
 10  bot_Push                  608 non-null    int64
 11  bot_IssueComments         608 non-null    int64
 12  eval_survival_day_median  303 non-null    float64
 13  issues_count              303 non-null    float64
dtypes: float64(4), int64(10)
memory usage: 66.6 KB

In [36]:
# Save the columns `Team_size_class` and `human_members_count` as a new DataFrame
new_df = gh_teams.loc[:, ['Team_size_class', 'human_members_count']]
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Team_size_class      608 non-null    category
 1   human_members_count  608 non-null    int64
dtypes: category(1), int64(1)
memory usage: 5.6 KB

In [37]:
# Rename these two columns in the new DataFrame
new_df.columns = ['Team_size_class_2', 'human_members_count_2']
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Team_size_class_2      608 non-null    category
 1   human_members_count_2  608 non-null    int64
dtypes: category(1), int64(1)
memory usage: 5.6 KB

## References

OpenAI. (2025). ChatGPT (GPT-4.0) [Large language model]. https://chatgpt.com/share/67fd6b24-0180-8000-bb27-221188dab19e